// Base de datos de temas para el juego de vocabulario
const themesDatabase = {
    "colores": {
        name: "🌈 Colores",
        icon: "🎨",
        words: {
            "red": ["rojo"],
            "blue": ["azul"],
            "green": ["verde"],
            "yellow": ["amarillo"],
            "black": ["negro"],
            "white": ["blanco"],
            "orange": ["naranja"],
            "purple": ["morado", "púrpura"],
            "pink": ["rosa", "rosado"],
            "brown": ["marrón", "café"],
            "gray": ["gris"],
            "silver": ["plateado", "plata"],
            "gold": ["dorado", "oro"]
        }
    },
    "numeros": {
        name: "🔢 Números",
        icon: "🧮",
        words: {
            "one": ["uno"],
            "two": ["dos"],
            "three": ["tres"],
            "four": ["cuatro"],
            "five": ["cinco"],
            "six": ["seis"],
            "seven": ["siete"],
            "eight": ["ocho"],
            "nine": ["nueve"],
            "ten": ["diez"],
            "twenty": ["veinte"],
            "thirty": ["treinta"],
            "fifty": ["cincuenta"],
            "hundred": ["cien"],
            "thousand": ["mil"]
        }
    },
    "cuerpo": {
        name: "👤 Partes del Cuerpo",
        icon: "🫵",
        words: {
            "head": ["cabeza"],
            "hand": ["mano"],
            "foot": ["pie"],
            "eye": ["ojo"],
            "mouth": ["boca"],
            "ear": ["oreja", "oído"],
            "nose": ["nariz"],
            "hair": ["cabello", "pelo"],
            "arm": ["brazo"],
            "leg": ["pierna"],
            "finger": ["dedo"],
            "tooth": ["diente"],
            "heart": ["corazón"],
            "stomach": ["estómago"],
            "back": ["espalda"],
            "neck": ["cuello"],
            "shoulder": ["hombro"],
            "knee": ["rodilla"]
        }
    },
    "tiempo": {
        name: "⏰ Tiempo",
        icon: "📅",
        words: {
            "day": ["día"],
            "night": ["noche"],
            "morning": ["mañana"],
            "afternoon": ["tarde"],
            "evening": ["noche", "atardecer"],
            "week": ["semana"],
            "month": ["mes"],
            "year": ["año"],
            "time": ["tiempo", "hora"],
            "hour": ["hora"],
            "minute": ["minuto"],
            "second": ["segundo"],
            "today": ["hoy"],
            "tomorrow": ["mañana"],
            "yesterday": ["ayer"],
            "weekend": ["fin de semana"]
        }
    },
    "lugares": {
        name: "🏙️ Lugares",
        icon: "🗺️",
        words: {
            "city": ["ciudad"],
            "country": ["país"],
            "world": ["mundo"],
            "street": ["calle"],
            "park": ["parque"],
            "hospital": ["hospital"],
            "restaurant": ["restaurante"],
            "school": ["escuela", "colegio"],
            "library": ["biblioteca"],
            "museum": ["museo"],
            "beach": ["playa"],
            "mountain": ["montaña"],
            "forest": ["bosque"],
            "river": ["río"],
            "lake": ["lago"],
            "airport": ["aeropuerto"],
            "station": ["estación"]
        }
    },
    "emociones": {
        name: "😊 Emociones",
        icon: "💭",
        words: {
            "happy": ["feliz", "alegre"],
            "sad": ["triste"],
            "angry": ["enojado", "enfadado"],
            "excited": ["emocionado", "entusiasmado"],
            "nervous": ["nervioso"],
            "calm": ["calmado", "tranquilo"],
            "surprised": ["sorprendido"],
            "worried": ["preocupado"],
            "tired": ["cansado"],
            "bored": ["aburrido"],
            "confused": ["confundido"],
            "proud": ["orgulloso"],
            "scared": ["asustado", "temeroso"],
            "relaxed": ["relajado"]
        }
    },
    "adjetivos": {
        name: "📏 Adjetivos",
        icon: "📊",
        words: {
            "big": ["grande"],
            "small": ["pequeño", "chico"],
            "good": ["bueno"],
            "bad": ["malo"],
            "hot": ["caliente"],
            "cold": ["frío"],
            "fast": ["rápido"],
            "slow": ["lento"],
            "beautiful": ["hermoso", "bonito", "bello"],
            "ugly": ["feo"],
            "important": ["importante"],
            "difficult": ["difícil"],
            "easy": ["fácil"],
            "new": ["nuevo"],
            "old": ["viejo"],
            "young": ["joven"],
            "tall": ["alto"],
            "short": ["bajo", "corto"],
            "rich": ["rico"],
            "poor": ["pobre"]
        }
    },
    "acciones": {
        name: "🏃 Acciones",
        icon: "⚡",
        words: {
            "run": ["correr"],
            "walk": ["caminar"],
            "eat": ["comer"],
            "drink": ["beber"],
            "sleep": ["dormir"],
            "work": ["trabajar"],
            "study": ["estudiar"],
            "play": ["jugar"],
            "love": ["amar", "querer"],
            "help": ["ayudar"],
            "read": ["leer"],
            "write": ["escribir"],
            "listen": ["escuchar"],
            "watch": ["ver", "mirar"],
            "speak": ["hablar"],
            "think": ["pensar"],
            "sing": ["cantar"],
            "dance": ["bailar"],
            "cook": ["cocinar"],
            "clean": ["limpiar"]
        }
    },
    "hogar": {
        name: "🏠 Hogar",
        icon: "🏘️",
        words: {
            "house": ["casa"],
            "home": ["hogar", "casa"],
            "room": ["habitación", "cuarto"],
            "kitchen": ["cocina"],
            "bathroom": ["baño"],
            "bedroom": ["dormitorio", "recámara"],
            "door": ["puerta"],
            "window": ["ventana"],
            "table": ["mesa"],
            "chair": ["silla"],
            "bed": ["cama"],
            "sofa": ["sofá", "sillón"],
            "television": ["televisión", "televisor"],
            "computer": ["computadora", "ordenador"],
            "phone": ["teléfono"],
            "book": ["libro"],
            "lamp": ["lámpara"],
            "mirror": ["espejo"]
        }
    },
    "conceptos": {
        name: "💭 Conceptos",
        icon: "🧠",
        words: {
            "possible": ["posible"],
            "impossible": ["imposible"],
            "problem": ["problema"],
            "solution": ["solución"],
            "question": ["pregunta"],
            "answer": ["respuesta"],
            "knowledge": ["conocimiento"],
            "experience": ["experiencia"],
            "opportunity": ["oportunidad"],
            "success": ["éxito"],
            "failure": ["fracaso", "falla"],
            "idea": ["idea"],
            "dream": ["sueño"],
            "hope": ["esperanza"],
            "fear": ["miedo", "temor"],
            "truth": ["verdad"],
            "lie": ["mentira"]
        }
    },
    "deportes": {
        name: "⚽ Deportes",
        icon: "🏆",
        words: {
            "football": ["fútbol"],
            "soccer": ["fútbol"],
            "basketball": ["baloncesto", "básquetbol"],
            "tennis": ["tenis"],
            "volleyball": ["voleibol"],
            "baseball": ["béisbol"],
            "swimming": ["natación"],
            "running": ["correr", "carrera"],
            "cycling": ["ciclismo"],
            "boxing": ["boxeo"],
            "golf": ["golf"],
            "hockey": ["hockey"],
            "player": ["jugador"],
            "team": ["equipo"],
            "match": ["partido"],
            "goal": ["gol", "meta"],
            "win": ["ganar"],
            "lose": ["perder"]
        }
    },
    "verbos": {
    name: "🏃‍♂️ Verbos",
    icon: "⚡",
    words: {
        "be": ["ser", "estar"],
        "have": ["tener", "haber"],
        "do": ["hacer"],
        "say": ["decir"],
        "get": ["obtener", "conseguir"],
        "make": ["hacer", "crear"],
        "go": ["ir"],
        "know": ["saber", "conocer"],
        "take": ["tomar", "llevar"],
        "see": ["ver"],
        "come": ["venir"],
        "think": ["pensar"],
        "look": ["mirar", "ver"],
        "want": ["querer"],
        "give": ["dar"],
        "use": ["usar"],
        "find": ["encontrar"],
        "tell": ["decir", "contar"],
        "ask": ["preguntar"],
        "work": ["trabajar"],
        "seem": ["parecer"],
        "feel": ["sentir"],
        "try": ["intentar", "tratar"],
        "leave": ["dejar", "salir"],
        "call": ["llamar"],
        "need": ["necesitar"],
        "become": ["convertirse", "llegar a ser"],
        "put": ["poner", "colocar"],
        "mean": ["significar"],
        "keep": ["mantener", "guardar"],
        "let": ["dejar", "permitir"],
        "begin": ["comenzar", "empezar"],
        "help": ["ayudar"],
        "talk": ["hablar"],
        "turn": ["girar", "voltear"],
        "start": ["comenzar", "empezar"],
        "show": ["mostrar", "enseñar"],
        "hear": ["oír", "escuchar"],
        "play": ["jugar", "tocar"],
        "run": ["correr"],
        "move": ["mover", "mudarse"],
        "live": ["vivir"],
        "believe": ["creer"],
        "hold": ["sostener", "aguantar"],
        "bring": ["traer"],
        "happen": ["pasar", "ocurrir"],
        "write": ["escribir"],
        "provide": ["proporcionar"],
        "sit": ["sentarse"],
        "stand": ["pararse", "estar de pie"],
        "lose": ["perder"],
        "pay": ["pagar"],
        "meet": ["conocer", "encontrarse"],
        "include": ["incluir"],
        "continue": ["continuar"],
        "set": ["establecer", "poner"],
        "learn": ["aprender"],
        "change": ["cambiar"],
        "lead": ["liderar", "conducir"],
        "understand": ["entender"],
        "watch": ["ver", "mirar"],
        "follow": ["seguir"],
        "stop": ["parar", "detener"],
        "create": ["crear"],
        "speak": ["hablar"],
        "read": ["leer"],
        "allow": ["permitir"],
        "add": ["agregar", "añadir"],
        "spend": ["gastar", "pasar tiempo"],
        "grow": ["crecer"],
        "open": ["abrir"],
        "walk": ["caminar"],
        "win": ["ganar"],
        "offer": ["ofrecer"],
        "remember": ["recordar"],
        "love": ["amar"],
        "consider": ["considerar"],
        "appear": ["aparecer"],
        "buy": ["comprar"],
        "wait": ["esperar"],
        "serve": ["servir"],
        "die": ["morir"],
        "send": ["enviar"],
        "expect": ["esperar"],
        "build": ["construir"],
        "stay": ["quedarse"],
        "fall": ["caer"],
        "cut": ["cortar"],
        "reach": ["alcanzar"],
        "kill": ["matar"],
        "remain": ["permanecer"],
        "suggest": ["sugerir"],
        "raise": ["levantar", "criar"],
        "pass": ["pasar"],
        "sell": ["vender"],
        "require": ["requerir"],
        "report": ["reportar"],
        "decide": ["decidir"],
        "pull": ["tirar", "jalar"],
        "break": ["romper"],
        "pick": ["elegir", "recoger"],
        "travel": ["viajar"],
        "drive": ["manejar", "conducir"],
        "dance": ["bailar"],
        "sing": ["cantar"],
        "eat": ["comer"],
        "drink": ["beber"],
        "sleep": ["dormir"],
        "cook": ["cocinar"],
        "clean": ["limpiar"],
        "wash": ["lavar"],
        "study": ["estudiar"],
        "teach": ["enseñar"],
        "listen": ["escuchar"],
        "answer": ["responder"],
        "choose": ["elegir"],
        "explain": ["explicar"],
        "share": ["compartir"],
        "save": ["salvar", "ahorrar"],
        "join": ["unirse"],
        "enjoy": ["disfrutar"],
        "hope": ["esperar"],
        "wish": ["desear"],
        "trust": ["confiar"],
        "doubt": ["dudar"]
    }
    },
    "conectores": {
        name: "🔗 Conectores",
        icon: "⛓️",
        words: {
            "and": ["y"],
            "or": ["o"],
            "but": ["pero"],
            "so": ["entonces", "así que"],
            "because": ["porque"],
            "if": ["si"],
            "when": ["cuando"],
            "while": ["mientras"],
            "before": ["antes"],
            "after": ["después"],
            "since": ["desde", "ya que"],
            "until": ["hasta"],
            "although": ["aunque"],
            "however": ["sin embargo"],
            "therefore": ["por lo tanto"],
            "moreover": ["además"],
            "also": ["también"],
            "first": ["primero"],
            "then": ["entonces", "luego"],
            "finally": ["finalmente"],
            "for example": ["por ejemplo"],
            "such as": ["como", "tal como"],
            "in addition": ["además"],
            "on the other hand": ["por otro lado"],
            "in conclusion": ["en conclusión"],
            "as a result": ["como resultado"],
            "meanwhile": ["mientras tanto"],
            "nevertheless": ["sin embargo", "no obstante"],
            "furthermore": ["además"],
            "consequently": ["por consiguiente"],
            "instead": ["en su lugar", "en cambio"],
            "otherwise": ["de lo contrario", "si no"],
            "besides": ["además", "aparte de"],
            "despite": ["a pesar de"],
            "unless": ["a menos que"],
            "whereas": ["mientras que"],
            "thus": ["así", "de esta manera"],
            "hence": ["por tanto", "de ahí"],
            "indeed": ["de hecho", "efectivamente"],
            "obviously": ["obviamente"],
            "clearly": ["claramente"],
            "actually": ["en realidad", "de hecho"],
            "basically": ["básicamente"],
            "generally": ["generalmente"],
            "specifically": ["específicamente"],
            "particularly": ["particularmente"],
            "especially": ["especialmente"],
            "rather": ["más bien", "en lugar de"],
            "instead of": ["en lugar de"],
            "due to": ["debido a"],
            "owing to": ["debido a"],
            "thanks to": ["gracias a"],
            "in spite of": ["a pesar de"],
            "regardless of": ["sin importar", "independientemente de"],
            "according to": ["según", "de acuerdo a"],
            "in order to": ["para", "con el fin de"],
            "so that": ["para que", "de modo que"],
            "in case": ["en caso de que"],
            "provided that": ["siempre que", "con tal de que"],
            "as long as": ["mientras", "siempre que"],
            "even if": ["aunque", "incluso si"],
            "even though": ["aunque", "a pesar de que"],
            "as well as": ["así como", "además de"],
            "not only": ["no solo", "no solamente"],
            "but also": ["sino también"],
            "either": ["o", "tampoco"],
            "neither": ["ni", "tampoco"],
            "both": ["ambos", "tanto"],
            "whether": ["si", "ya sea"],
            "wherever": ["dondequiera que"],
            "whenever": ["cuando sea que", "siempre que"],
            "whatever": ["lo que sea", "cualquier cosa"],
            "whoever": ["quienquiera que"],
            "however": ["sin embargo", "como sea que"],
            "whichever": ["cualquiera que"],
            "in fact": ["de hecho"],
            "of course": ["por supuesto", "claro"],
            "by the way": ["por cierto"],
            "on the contrary": ["por el contrario"],
            "at the same time": ["al mismo tiempo"],
            "at first": ["al principio"],
            "at last": ["por fin", "al final"],
            "in the end": ["al final"],
            "above all": ["sobre todo"],
            "after all": ["después de todo"],
            "all in all": ["en general", "en resumen"],
            "as usual": ["como siempre", "como de costumbre"],
            "for instance": ["por ejemplo"],
            "that is": ["es decir"],
            "in other words": ["en otras palabras"],
            "to sum up": ["para resumir"],
            "overall": ["en general"],
            "likewise": ["igualmente", "de la misma manera"],
            "similarly": ["de manera similar"],
            "conversely": ["por el contrario"],
            "on the whole": ["en general"],
            "in brief": ["en resumen"],
            "in short": ["en pocas palabras"]
        }
    },
    "Anexos": {
        name: "Mías",
        icon: "🧮",
        words: {
                "odd": ["extraño"],
        "hijack it": ["secuestrarlo"],
        "fasten seatbelts": ["abróchense los cinturones"],
        "restrain": ["contener"],
        "turd": ["mierda"],
        "runnerup": ["subcampeón"],
        "whats goku up to?": ["¿Qué está tramando Goku?"],
        "deadlines": ["plazos"],
        "darn fool": ["maldito tonto"],
        "did it just slipped his mind?": ["¿Se le olvidó?"],
        "he was looking forward to this": ["Él estaba esperando esto con ansias"],
        "it's no use": ["No sirve de nada"],
        "nasty as ever": ["desagradable como siempre"],
        "have gotten pretty pathetic": ["Se han vuelto bastante patéticos"],
        "i'll be looking forward to the matches": ["Estaré esperando con ansias los partidos"],
        "loathsome": ["repugnante"],
        "former rival": ["ex rival"],
        "that so?": ["eso es asi?"],
        "hall": ["sala"],
        "im not gonna be outdone": ["No voy a ser superado"],
        "from this party onward it": ["A partir de esta fiesta en adelante"],
        "will be held": ["se llevará a cabo"],
        "even so": ["aún así"],
        "very harsh": ["muy duro"],
        "nvm": ["no importa"],
        "for here or to go?": ["¿Para aquí o para llevar?"],
        "right off the bat": ["inmediatamente"],
        "toughened up": ["endurecido"],
        "snotty ain't ya?": ["Presumida, ¿no?"],
        "naive": ["ingenuo"],
        "either way": ["de cualquier manera"],
        "spunk": ["coraje"],
        "tyke": ["perro de calle"],
        "goofed up": ["metió la pata"],
        "ya' fell for it": ["Caíste en la trampa"],
        "blast": ["explosión"],
        "expelling his breath": ["expulsando su aliento"],
        "he brought down king so easily": ["Derribó al rey tan fácilmente"],
        "worn out": ["desgastado"],
        "all out": ["con todas las fuerzas", "completamente"],
        "ever fewer": ["cada vez menos"],
        "gaping": ["boquiabierto"],
        "pointless bickering": ["Discusiones sin sentido"],
        "participants please assemble": ["Las participantes por favor se reúnen"],
        "bumped off so soon": ["eliminado tan pronto"],
        "ribbon": ["cinta"],
        "is it?": ["¿lo es?"],
        "old timers gone off somewhere again": ["Los viejos se fueron a algún lado otra vez"],
        "don't lump me in with that dope": ["No me metas en el mismo saco que a ese idiota"],
        "be out cold": ["estar inconsciente"],
        "you think so": ["Tú crees eso"],
        "i told ya that ain't so": ["Te dije que no es así"],
        "jus that brief instant": ["Sólo ese breve instante"],
        "darn": ["maldito"],
        "ace in the hole": ["as en la manga"],
        "breathtakingly": ["Impresionantemente"],
        "he knocked it back": ["Él lo tiró hacia atrás"],
        "take him to a hospital at once": ["Llévelo a un hospital de inmediato"],
        "place him on me": ["Colócalo sobre mí"],
        "avenge yamcha in the ring": ["vengar a yamcha en el ring"],
        "grudge": ["envidiar"],
        "face off": ["enfrentarse"],
        "is that it?": ["es eso todo?"],
        "mock": ["burlarse de"],
        "crap": ["cagada", "tonterías", "mierda"],
        "aren't you gonna count?": ["¿No vas a contar?"],
        "stubborn": ["obstinado", "terco"],
        "short tempered": ["de mal genio"],
        "surrender": ["rendirse"],
        "next up": ["A continuación"],
        "at will": ["A voluntad"],
        "bounds": ["limites"],
        "helpless": ["indefenso"],
        "fair warning": ["Advertencia justa"],
        "showoff": ["presumida"],
        "underway": ["En marcha"],
        "grasp victory": ["Alcanzar la victoria"],
        "blow": ["golpe"],
        "what's it to yo?": ["¿A ti qué te importa?"],
        "badmouth my master": ["hablar mal de mi amo"],
        "despise": ["despreciar"],
        "in disguise": ["disfrazado"],
        "waste": ["desperdiciar"],
        "foolish": ["Tonto", "necio"],
        "spoiled": ["arruinado"],
        "squeeze": ["apretar"],
        "HELLO": ["HOLA"],
        "AS": ["SD"],
        "cripes": ["caramba"],
        "medicine": ["medicina"],
        "pose": ["posa"],
        "presentation": ["presentación"],
        "one could even say wild": ["Se podría incluso decir salvaje"],
        "vanish": ["desaparecer", "esfumarse"],
        "brat": ["mocoso"],
        "blowing me away": ["me deja sin aliento"],
        "will it be contestant tian who obtains": ["¿Será el concursante Tian quien obtenga?"],
        "summits": ["cumbres"],
        "childish trick": ["truco infantil"],
        "finish you off": ["acabar contigo"],
        "unleashed": ["soltado"],
        "babble": ["balbucear", "murmurllo"],
        "wrinkly": ["arrugado"],
        "owe": ["deber algo"],
        "i thought so": ["Ya me lo imaginaba"],
        "lifespan": ["esperanza de vida"],
        "endangers": ["pone en peligro"],
        "own": ["propio", "propia"],
        "i'll treat you all": ["Los invitaré a todos"],
        "plunged the world into": ["sumió al mundo en"],
        "devise": ["idear"],
        "everlast": ["eterna"],
        "rely": ["confiar"],
        "what are you getting at?": ["¿A qué quieres llegar?"],
        "seal": ["sellar"],
        "most likely": ["lo más probable"],
        "bleak": ["desolado", "desolada"],
        "devoid of": ["Desprovista de"],
        "conquer": ["conquistar"],
        "fountain": ["Fuente"],
        "hatch": ["salir del cascarón"],
        "relieve": ["aliviar"],
        "i have a score to settle": ["Tengo una cuenta que saldar"],
        "you think this is recess?": ["¿Crees que esto es el recreo?"],
        "you disappoint me": ["Me decepcionas"],
        "unthinkable": ["inconcebible"],
        "we will get to that": ["Nosotros llegaremos a eso"],
        "wipe the floor": ["Limpiar el piso"],
        "you don't deserve the confidence I placed in you": ["No mereces la confianza que deposité en ti"],
        "wrath": ["ira"],
        "it must be a trap": ["Debe ser una trampa"],
        "you shouldn't taunt": ["no deberías burlarte"],
        "summon": ["convocar"],
        "feast": ["banquete"],
        "rule over": ["gobernar sobre"],
        "hold on tight": ["Agárrate fuerte"],
        "backfired": ["fue contraproducente"],
        "i'm getting really sore": ["Me estoy poniendo muy dolorido"],
        "come along quietly": ["ven en silencio"],
        "without equal": ["sin igual"],
        "rot": ["pudrir"],
        "have it your way": ["Hazlo a tu manera"],
        "discourage": ["desalentar"],
        "dethroned me": ["me destronó"],
        "are hereby outlawed": ["prohibidos"],
        "hereby": ["por la presente"],
        "in the blink of an eye": ["En un abrir y cerrar de ojos"],
        "novice": ["principiante"],
        "how amusing": ["que divertido"],
        "insolent twerp": ["imbécil insolente"],
        "the end is sight": ["El final es la vista"],
        "the end is in sight": ["El final está a la vista"],
        "you are of no use to me": ["No me sirves de nada"],
        "how reassuring": ["que tranquilizador"],
        "Im off": ["see you", "bye"],
        "scarce": ["escaso"],
        "they misused": ["Ellos hicieron mal uso"],
        "seems so": ["Parece que sí"],
        "deadly": ["letal", "mortal"],
        "we think alike": ["Nosotras pensamos igual"],
        "he looks fired up": ["Él parece entusiasmado"],
        "strangely resembles mine": ["Extrañamente se parece a la mia"],
        "engaged": ["comprometido"],
        "i overdone a little": ["Me excedí un poco"],
        "whenever": ["cuando sea"],
        "harmless": ["inofensivo"],
        "unlike yours": ["a diferencia del tuyo"],
        "i awakened you, haven't?": ["Te desperté, ¿no?"],
        "uselessly": ["inútilmente"],
        "unharmed": ["ileso"],
        "flaws": ["defectos"],
        "one for gossip": ["uno para chismes"],
        "root": ["raíz"],
        "alike": ["similar"],
        "widow": ["viuda"],
        "the fate of the entire world is at stake": ["El destino del mundo entero está en juego"],
        "you could tell?": ["¿Podrías decirlo?"],
        "torn to shreds": ["Rasgada en pedazos"],
        "eager": ["ansioso"],
        "along with": ["junto con"],
        "rashly": ["precipitadamente"],
        "lay": ["poner"],
        "slaughter": ["sacrificio", "matar"],
        "obliterated": ["borrada"],
        "knock it off": ["déjalo ya"],
        "herd": ["multitud"],
        "is that so?": ["¿Es eso así?"],
        "feather": ["pluma"],
        "confident": ["seguro"],
        "seemingly": ["aparentemente"],
        "flipp": ["voltear"],
        "arrange": ["organizar"],
        "limbs": ["extremidades"],
        "pile of ash": ["montón de ceniza"],
        "fussy about that": ["Molesta por eso"],
        "turned out to be": ["Resultó ser"],
        "tame": ["domar"],
        "earthling": ["terricola"],
        "picture it carlos": ["Imagínatelo Carlos"],
        "wiping out": ["acabar con"],
        "stacked": ["apilada"],
        "hostage": ["rehén"],
        "the choice is his": ["La elección es suya"],
        "off the charts": ["fuera de serie"],
        "however unlikely": ["Sin embargo, es poco probable"],
        "nothing up my sleeve": ["No tengo nada bajo la manga"],
        "chills": ["escalofríos"],
        "this is hardly the time to be laughing": ["Este no es el momento para reírse"],
        "pierce": ["atravesar"],
        "beget": ["engendrar"],
        "have a fit": ["tener un ataque"],
        "seek out": ["buscar"],
        "quit whining": ["Deja de quejarte"],
        "curse your own fate": ["maldice tu propio destino"],
        "bound": ["atada"],
        "foreseeing": ["previendo"],
        "filthy": ["asqueroso"],
        "brace yourself": ["Prepárate"],
        "clansman": ["miembro del clan"],
        "the hang of things": ["El truco de las cosas"],
        "sight": ["vista"],
        "gag": ["broma"],
        "outdo me": ["supérame"],
        "wretched": ["miserable"],
        "i've yearned of": ["he anhelado"],
        "hour draws near": ["la hora se acerca"],
        "last resort": ["último recurso"],
        "snazziest": ["el más elegante"],
        "is banged up": ["Está golpeado"],
        "spit": ["escupir"],
        "sigh": ["suspirar"],
        "single mindedly": ["con un solo propósito"],
        "wreck": ["ruina"],
        "fret over": ["Preocuparse por"],
        "junk": ["chatarra"],
        "adamantly": ["rotundamente"],
        "sassy": ["atrevido"],
        "get rid": ["Deshazte"],
        "foe": ["enemigo"],
        "fill her in": ["ponerla al corriente"],
        "barely able": ["apenas capaz"],
        "where are you off to": ["¿A dónde vas?"],
        "forsake": ["dejar", "abandonar"],
        "spit it out": ["escúpelo"],
        "armpits": ["axilas"],
        "itch": ["picazón", "picar"],
        "pantorrillas": ["calves"],
        "pesan": ["weigh"],
        "in turn": ["a su vez"],
        "for instance": ["por ejemplo"],
        "forecast": ["pronóstico"],
        "shrink": ["encodigo", "achicarse"],
        "addressed": ["abordado"],
        "charting": ["trazando"],
        "be it": ["sea"],
        "raw material": ["materia prima"],
        "foray": ["incursión"],
        "yield": ["rendimiento"],
        "hence": ["por lo tanto"],
        "headhunt": ["Reclutamiento de talentos"],
        "setback": ["Contratiempo"],
        "is at hand": ["está cerca", "está al alcance"],
        "stuffed animals": ["animales de peluche"],
        "tightwad": ["tacaño"],
        "unhand that child": ["suelta a ese niño"],
        "has come in handy": ["ha sido util", "ha venido bien"],
        "too lax": ["Demasiado relajado"],
        "you are quite a sight yourself": ["tu tambien das de que hablar"],
        "burst": ["estallar", "reventar"],
        "Hola": ["Hello"],
        "car": ["carro"],
        "shed": ["cobertizo"],
        "atches": ["atascos"],
        "aches": ["dolores"],
        "vow": ["promesa", "prometer", "voto"],
        "laid out in a grid": ["dispuesto en una cuadrícula"],
        "worth 5 points": ["vale 5 puntos"],
        "hop over": ["saltar por encima"],
        "promote your pawn to a queen": ["promueve tu peón a reina"],
        "newcomers": ["Recién llegadas"],
        "as of": ["a partir de"],
        "global trade": ["Comercio mundial"],
        "prompting": ["incitación"],
        "revenue": ["ganancias"],
        "bargaining chips": ["moneda de cambio"],
        "biased": ["sesgado"],
        "ripped off": ["estado"],
        "at stake": ["en juego"]  
        }
    },
    "aeropuerto": {
    "name": "✈️ Aeropuerto",
    "icon": "🛄",
    "words": {
        "travel": ["viajar"],
        "fly": ["volar"],
        "pack": ["empacar"],
        "unpack": ["desempacar"],
        "board": ["abordar", "subir al avión"],
        "check in": ["registrarse", "hacer el check-in"],
        "check in luggage": ["facturar equipaje"],
        "go through security": ["pasar por seguridad"],
        "take off": ["despegar"],
        "land": ["aterrizar"],
        "lay over": ["hacer escala"],
        "wait": ["esperar"],
        "book": ["reservar"],
        "cancel": ["cancelar"],
        "miss the flight": ["perder el vuelo"],
        "show": ["mostrar"],
        "sit down": ["sentarse"],
        "stand up": ["levantarse"],
        "claim baggage": ["recoger el equipaje"],
        "declare": ["declarar"],
        "fill out": ["llenar (formularios)"],
        "go through customs": ["pasar por aduana"],
        "delay": ["retrasarse"],
        "arrive": ["llegar"],
        "depart": ["salir"],
        "scan": ["escanear"],
        "announce": ["anunciar"],
        "airport": ["aeropuerto"],
        "airplane": ["avión"],
        "ticket": ["boleto", "billete"],
        "passport": ["pasaporte"],
        "visa": ["visa"],
        "boarding pass": ["tarjeta de embarque"],
        "luggage": ["equipaje"],
        "suitcase": ["maleta"],
        "carry-on bag": ["bolso de mano"],
        "check-in counter": ["mostrador de check-in"],
        "waiting room": ["sala de espera"],
        "departure lounge": ["sala de embarque"],
        "gate": ["puerta de embarque"],
        "control tower": ["torre de control"],
        "runway": ["pista de aterrizaje"],
        "customs": ["aduana"],
        "immigration": ["inmigración"],
        "security": ["seguridad"],
        "cabin": ["cabina"],
        "seat": ["asiento"],
        "window": ["ventana"],
        "aisle": ["pasillo"],
        "pilot": ["piloto"],
        "crew": ["tripulación"],
        "flight attendant": ["azafata", "asistente de vuelo"],
        "passenger": ["pasajero"],
        "flight": ["vuelo"],
        "connecting flight": ["vuelo de conexión"],
        "itinerary": ["itinerario"],
        "delay (noun)": ["retraso"],
        "announcement": ["anuncio"],
        "turbulence": ["turbulencia"],
        "lost luggage": ["pérdida de equipaje"],
        "cancelled flight": ["vuelo cancelado"],
        "delayed flight": ["vuelo retrasado"],
        "emergency": ["emergencia"],
        "first aid": ["primeros auxilios"],
        "help": ["ayuda"],
        "information": ["información"],
        "travel insurance": ["seguro de viaje"],
        "document": ["documento"],
        "emergency seat": ["asiento de emergencia"],
        "flight change": ["cambio de vuelo"],
        "customs form": ["formulario de aduana"],
        "baggage claim": ["reclamo de equipaje"],
        "arrival": ["llegada"],
        "departure": ["salida"],
        "delay": ["demora"],
        "carry-on": ["equipaje de mano"]
    }
},

};
